### ISSUE TITLE
Both power pins connected to 5v in image

### ISSUE THREAD

**Issue by sduff** [fire1ce/raspberry-pi-pir-motion-screen-control#2]
In your image, both leads (blue and yellow) are connected to 5v power pins (pins 2 and 4).
In reality, the yellow lead  should be connected to pin 6, Ground

😄

**Comment by fire1ce** [comment]
dman. you are right. ill need to taka a new pic today and fix it. 
thanks =)

**Comment by fire1ce** [comment]
I've fixed the pic. thanks again
